CREATE TABLE PERSON (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    BIRTH_DATE TIMESTAMP(6) NULL,
    EMAIL VARCHAR(255) NOT NULL,
    GENDER VARCHAR(10) NOT NULL
);
